//HintName: Game.Screens.Inventory.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.Screens.Inventory
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_Screens_Inventory
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.Screens.Inventory),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.Screens.Inventory, int>("Gold", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Gold, static (vm, value) => vm.Gold.Value = value),
                },
                null,
                static services => new global::Game.Screens.Inventory(global::GodotHat.Binding.ServiceResolver.Required<int>(services, typeof(global::Game.Screens.Inventory)))));
        }
    }
}
