//HintName: Game.Entry.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.Entry
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_Entry
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.Entry),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.ConstantMember<global::Game.Entry, string>("Title", static vm => vm.Title),
                },
                null,
                null));
        }
    }
}
