//HintName: Game.ClockViewModel.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.ClockViewModel
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_ClockViewModel
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.ClockViewModel),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.ClockViewModel, int>("Ticks", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Ticks, static (vm, value) => vm.Ticks.Value = value),
                },
                static () => new global::Game.ClockViewModel(),
                static services => new global::Game.ClockViewModel(global::GodotHat.Binding.ServiceResolver.Required<global::Game.IClock>(services, typeof(global::Game.ClockViewModel)), global::GodotHat.Binding.ServiceResolver.Optional<global::Game.ILog?>(services), services)));
        }
    }
}
