//HintName: Game.DetailPageViewModel.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.DetailPageViewModel
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_DetailPageViewModel
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.DetailPageViewModel),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.DetailPageViewModel, string>("Title", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Title, static (vm, value) => vm.Title.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.DetailPageViewModel, int>("Page", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Page, static (vm, value) => vm.Page.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.DetailPageViewModel, bool>("Busy", global::GodotHat.Binding.MemberKind.ReadOnlyProperty, static vm => vm.Busy),
                    new global::GodotHat.Binding.PropertyMember<global::Game.DetailPageViewModel, string>("Detail", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Detail, static (vm, value) => vm.Detail.Value = value),
                },
                static () => new global::Game.DetailPageViewModel(),
                static services => new global::Game.DetailPageViewModel()));
        }
    }
}
