//HintName: Game.Ui.ChildViewModel.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.Ui.ChildViewModel
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_Ui_ChildViewModel
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.Ui.ChildViewModel),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ChildViewModel, string>("Label", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Label, static (vm, value) => vm.Label.Value = value),
                },
                static () => new global::Game.Ui.ChildViewModel(),
                static services => new global::Game.Ui.ChildViewModel()));
        }
    }
}
