//HintName: Game.AbstractViewModel.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.AbstractViewModel
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_AbstractViewModel
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.AbstractViewModel),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.AbstractViewModel, int>("Value", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Value, static (vm, value) => vm.Value.Value = value),
                },
                null,
                null));
        }
    }
}
