//HintName: Game.Ui.ScreenViewModel.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.Ui.ScreenViewModel
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_Ui_ScreenViewModel
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.Ui.ScreenViewModel),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, int>("Count", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Count, static (vm, value) => vm.Count.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, float>("Volume", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Volume, static (vm, value) => vm.Volume.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, bool>("HasItems", global::GodotHat.Binding.MemberKind.ReadOnlyProperty, static vm => vm.HasItems),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, string>("Search", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Search.AsObservable(), static (vm, value) => vm.Search.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, string>("Status", global::GodotHat.Binding.MemberKind.ReadOnlyProperty, static vm => vm.Status.AsObservable()),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, long>("Ticks", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Ticks, static (vm, value) => vm.Ticks.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, string>("Toasts", global::GodotHat.Binding.MemberKind.Observable, static vm => vm.Toasts),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, global::R3.Unit>("Flashed", global::GodotHat.Binding.MemberKind.Observable, static vm => vm.Flashed),
                    new global::GodotHat.Binding.CommandMember<global::Game.Ui.ScreenViewModel, global::R3.Unit>("Clear", static vm => vm.Clear, static (vm, parameter) => vm.Clear.Execute(parameter)),
                    new global::GodotHat.Binding.CommandMember<global::Game.Ui.ScreenViewModel, int>("Remove", static vm => vm.Remove, static (vm, parameter) => vm.Remove.Execute(parameter)),
                    new global::GodotHat.Binding.CommandMember<global::Game.Ui.ScreenViewModel, string>("Parse", static vm => vm.Parse, static (vm, parameter) => vm.Parse.Execute(parameter)),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.Mood>("Mood", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Mood, static (vm, value) => vm.Mood.Value = value),
                    new global::GodotHat.Binding.PropertyMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.ChildViewModel?>("Selected", global::GodotHat.Binding.MemberKind.ReactiveProperty, static vm => vm.Selected, static (vm, value) => vm.Selected.Value = value),
                    new global::GodotHat.Binding.ConstantMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.ChildViewModel>("Header", static vm => vm.Header),
                    new global::GodotHat.Binding.CollectionItemsMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.ChildViewModel>("Children", static vm => vm.Children),
                    new global::GodotHat.Binding.CollectionItemsMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.Mood>("Moods", static vm => vm.Moods),
                    new global::GodotHat.Binding.CollectionItemsMember<global::Game.Ui.ScreenViewModel, global::System.Collections.Generic.KeyValuePair<string, int>>("Stock", static vm => vm.Stock),
                    new global::GodotHat.Binding.ViewItemsMember<global::Game.Ui.ScreenViewModel, global::Game.Ui.ChildViewModel, string>("Labels", static vm => vm.Labels),
                    new global::GodotHat.Binding.ConstantMember<global::Game.Ui.ScreenViewModel, string>("Title", static vm => vm.Title),
                    new global::GodotHat.Binding.ConstantMember<global::Game.Ui.ScreenViewModel, int>("class", static vm => vm.@class),
                },
                static () => new global::Game.Ui.ScreenViewModel(),
                static services => new global::Game.Ui.ScreenViewModel()));
            global::GodotHat.Binding.BindingRegistry.RegisterEnum(new global::GodotHat.Binding.EnumInfo<global::Game.Ui.Mood>(
                new global::Game.Ui.Mood[] { global::Game.Ui.Mood.Happy, global::Game.Ui.Mood.Sad, global::Game.Ui.Mood.@event },
                new string[] { "Happy", "Sad", "event" }));
        }
    }
}
