//HintName: Game.Tag.ViewModelAccessor.g.cs
// <auto-generated/>
// Generated by GodotHat.Binding.SourceGenerators for global::Game.Tag
#nullable enable
#pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

namespace GodotHat.Binding.Generated
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class ViewModelAccessor_Game_Tag
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register()
        {
            global::GodotHat.Binding.BindingRegistry.Register(new global::GodotHat.Binding.ViewModelAccessor(
                typeof(global::Game.Tag),
                new global::GodotHat.Binding.MemberAccessor[]
                {
                    new global::GodotHat.Binding.ConstantMember<global::Game.Tag, string>("Label", static vm => vm.Label),
                    new global::GodotHat.Binding.ConstantMember<global::Game.Tag, int>("Uses", static vm => vm.Uses),
                },
                null,
                static services => new global::Game.Tag(global::GodotHat.Binding.ServiceResolver.Required<string>(services, typeof(global::Game.Tag)), global::GodotHat.Binding.ServiceResolver.Required<int>(services, typeof(global::Game.Tag)))));
        }
    }
}
