<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Common.props" />
    
    <PropertyGroup>
        <Description>Attributes that are processed by GodotHat.SourceGenerators.</Description>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GodotSharp" Version="4.6.0-dev.3" />
        <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.14.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Analyzers" Version="4.14.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    </ItemGroup>

</Project>
