<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Common.props" />
    
    <PropertyGroup>
        <Description>Attributes that are processed by GodotHat.SourceGenerators.</Description>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.12.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
