using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GodotHat.Binding.SourceGenerators;

/// <summary>
/// Emits a typed accessor for each <c>[ViewModel]</c> class, registered with <c>BindingRegistry</c> by a module
/// initializer. Nothing is added to the view model itself.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ViewModelGenerator : IIncrementalGenerator
{
    internal const string TrackingName = "ViewModels";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ViewModelModel> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ViewModelModelBuilder.ViewModelAttributeName,
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, ct) => ViewModelModelBuilder.Build((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation, ct))
            .WithTrackingName(TrackingName);

        context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model));
    }

    private static void Emit(SourceProductionContext context, ViewModelModel model)
    {
        foreach (DiagnosticInfo diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.Emit)
        {
            context.AddSource($"{model.HintName}.ViewModelAccessor.g.cs", Render(model));
        }
    }

    internal static string Render(ViewModelModel model)
    {
        const string ns = "global::GodotHat.Binding";
        string owner = model.TypeName;
        var source = new StringBuilder();
        source.Append($$"""
            // <auto-generated/>
            // Generated by GodotHat.Binding.SourceGenerators for {{owner}}
            #nullable enable
            #pragma warning disable CA2255 // ModuleInitializer is how generated accessors register themselves

            namespace GodotHat.Binding.Generated
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                internal static class {{model.GeneratedClassName}}
                {
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void Register()
                    {
                        {{ns}}.BindingRegistry.Register(new {{ns}}.ViewModelAccessor(
                            typeof({{owner}}),
                            new {{ns}}.MemberAccessor[]
                            {

            """);

        foreach (MemberModel member in model.Members)
        {
            string name = ViewModelModelBuilder.EscapeIdentifier(member.Name);
            string type = member.ValueType;
            string line = member.Category switch
            {
                MemberCategory.ReactiveProperty =>
                    $"new {ns}.PropertyMember<{owner}, {type}>(\"{member.Name}\", {ns}.MemberKind.ReactiveProperty, static vm => vm.{name}, static (vm, value) => vm.{name}.Value = value)",
                MemberCategory.BindableProperty =>
                    $"new {ns}.PropertyMember<{owner}, {type}>(\"{member.Name}\", {ns}.MemberKind.ReactiveProperty, static vm => vm.{name}.AsObservable(), static (vm, value) => vm.{name}.Value = value)",
                MemberCategory.ReadOnlyProperty =>
                    $"new {ns}.PropertyMember<{owner}, {type}>(\"{member.Name}\", {ns}.MemberKind.ReadOnlyProperty, static vm => vm.{name})",
                MemberCategory.ReadOnlyBindableProperty =>
                    $"new {ns}.PropertyMember<{owner}, {type}>(\"{member.Name}\", {ns}.MemberKind.ReadOnlyProperty, static vm => vm.{name}.AsObservable())",
                MemberCategory.Observable =>
                    $"new {ns}.PropertyMember<{owner}, {type}>(\"{member.Name}\", {ns}.MemberKind.Observable, static vm => vm.{name})",
                MemberCategory.Command =>
                    $"new {ns}.CommandMember<{owner}, {type}>(\"{member.Name}\", static vm => vm.{name}, static (vm, parameter) => vm.{name}.Execute(parameter))",
                MemberCategory.Collection =>
                    $"new {ns}.CollectionItemsMember<{owner}, {type}>(\"{member.Name}\", static vm => vm.{name})",
                MemberCategory.View =>
                    $"new {ns}.ViewItemsMember<{owner}, {member.SourceType}, {type}>(\"{member.Name}\", static vm => vm.{name})",
                _ =>
                    $"new {ns}.ConstantMember<{owner}, {type}>(\"{member.Name}\", static vm => vm.{name})",
            };
            source.Append("                    ").Append(line).Append(",\n");
        }

        source.Append("                },\n");
        source.Append(model.CanCreate ? $"                static () => new {owner}(),\n" : "                null,\n");
        if (model.ServiceParameters is { } parameters)
        {
            string arguments = string.Join(", ", parameters.Select(p => p.Source switch
            {
                ParameterSource.ServiceProvider => "services",
                ParameterSource.Optional => $"{ns}.ServiceResolver.Optional<{p.Type}>(services)",
                _ => $"{ns}.ServiceResolver.Required<{p.Type}>(services, typeof({owner}))",
            }));
            source.Append($"                static services => new {owner}({arguments})));\n");
        }
        else
        {
            source.Append("                null));\n");
        }

        foreach (EnumModel @enum in model.Enums)
        {
            string values = string.Join(", ", @enum.Members.Select(m => $"{@enum.Type}.{ViewModelModelBuilder.EscapeIdentifier(m)}"));
            string names = string.Join(", ", @enum.Members.Select(m => $"\"{m}\""));
            source.Append($"            {ns}.BindingRegistry.RegisterEnum(new {ns}.EnumInfo<{@enum.Type}>(\n");
            source.Append($"                new {@enum.Type}[] {{ {values} }},\n");
            source.Append($"                new string[] {{ {names} }}));\n");
        }

        source.Append("""
                    }
                }
            }

            """);
        return source.ToString();
    }
}
