name: Build Release and Deploy
on:
  create:
    tags:
    - '*'

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "5.x"
      - name: Get built packages
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: "${{jobs.build.outputs.run_id}}"
          name: nupkgs-release
          path: nupkgs
          if_no_artifact_found: fail
      - name: Publish nupkgs
        run: |
          cd nupkgs
          ls -l
          nuget push '*.nupkg' -Source https://api.nuget.org/v3/index.json
