name: Build Release and Deploy
on:
  create:
    tags:
    - '*'
  release:
    types: [published]

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "5.x"
      - name: Get built packages
        uses: actions/download-artifact@v2
        with:
          name: nupkgs-release
      - name: Publish nupkgs
        run: |
          ls -l
          nuget push '*.nupkg' -Source https://api.nuget.org/v3/index.json
